{{- if .Values.dash0.enabled }}
apiVersion: operator.dash0.com/v1beta1
kind: Dash0Monitoring
metadata:
  name: dash0-monitoring-resource
  namespace: {{ .Release.Namespace }}
spec:
  instrumentWorkloads:
    mode: all
  logCollection:
    enabled: true
  prometheusScraping:
    enabled: true
  eventCollection:
    enabled: true
  synchronizePersesDashboards: true
  synchronizePrometheusRules: true
{{- end }}
